### ISSUE TITLE
Estimating RI means and syntax related question

### ISSUE THREAD

**Issue by miiroth** [JeroenDMulder/RI-CLPM#1]
Hi!

I am using RI-CLPM to study bidirectional associations between relationship satisfaction and gratitude. I have a conceptual question as well as questions related to the syntax for conducting a RI-CLPM.

Conceptual: I found other syntax where a mean structure is implemented (and error variances of observed variables are set to zero) in order to get estimates of intercept means which, to me, looks interesting. However, I was wondering what the pro/cons for one or the other way of modeling a RI-CLMP are? 

Question to your syntax: 
# Estimate (residual) variance of within-person centered variables
  wx1 ~~ wx1 # Variances
  wy1 ~~ wy1 
  wx2 ~~ wx2 # Residual variances

here I was wondering why the first line is described as a variance and the same code for time point 2 is described as a residual variance?

Best and thank you in advance
Michelle

**Comment by JeroenDMulder** [comment]
Hi Michelle,

1. The RI-CLPM specification on the website also constrains the error variances of the observed variables to 0. See the comment `! Constrain measurement error variances to 0` in the Mplus syntax. For the `lavaan` code, the error variances are 0 because we simply do not specify this parameter in the model specification. Additionally, the mean structure is typically not of interest when researchers plan on using the RI-CLPM (it is actually the same as the sample means in the RI-CLPM, as model is provided for it). In the Mplus syntax on the website we do not estimate the means, but in the `lavaan` code we do (see the `meanstructure = T` argument). However, there are cross-lagged panel models that do explicitly model the mean structure. See, for example, the bivariate latent curve model with structured residuals (for an overview of alternatives to the RI-CLPM, see [Usami, Murayama, and Hamaker, 2019](http://dx.doi.org/10.1037/met0000210)). 
2. The lines `wx1 ~~ wx1` and `wy1 ~~ wy1` specify variances because these variables are exogenous: They are not predicted themselves and therefore no residual is involved. However, the within-components at wave 2 are being predicted, and hence get a residual (because predicting is hardly ever perfect). In SEM you then estimate the variance of the residual, rather than the variance of the within-component itself. Hence the comment `# Residual variances`.

**Comment by miiroth** [comment]
Hi Jeroen

Thank you so much for this helpful reply! 

Best
Michelle
