### ISSUE TITLE
Is it possible to test mediation effects while runing RI-CLPM with three outcomes?

### ISSUE THREAD

**Issue by psyhtbian** [JeroenDMulder/RI-CLPM#2]
My variables contained the independent variable X, the mediation variable M, and the dependent variable Y, all of which were measured three times. I added X1 and Y3 and the path between Y1 and X3 hoping to test the mediation effect in X1M2Y3 and Y1M2X3, and tried using the bootstrap code, which seems to be operationally feasible.I want to know if this is statistically possible. And are the results provided by Mplus credible?

**Comment by psyhtbian** [comment]
When adding the path X1->Y3 and Y1->X3，Mplus result displayed warning.

     WARNING:  THE LATENT VARIABLE COVARIANCE MATRIX (PSI) IS NOT POSITIVE
     DEFINITE.  THIS COULD INDICATE A NEGATIVE VARIANCE/RESIDUAL VARIANCE FOR A
     LATENT VARIABLE, A CORRELATION GREATER OR EQUAL TO ONE BETWEEN TWO LATENT
     VARIABLES, OR A LINEAR DEPENDENCY AMONG MORE THAN TWO LATENT VARIABLES.
     CHECK THE TECH4 OUTPUT FOR MORE INFORMATION.
     PROBLEM INVOLVING VARIABLE RIY.

**Comment by psyhtbian** [comment]
I read the article you mentioned Hygen et al. (2022) on your homepage, and I found that although they mentioned "Mediation effects" in the article, but they did not conduct bootstrap analysis. What should I do to get the results of the mediation analysis correctly, and look forward to your answer.

Hygen et al. (2022):https://www.sciencedirect.com/science/article/pii/S0747563222000747?via%3Dihub

**Comment by JeroenDMulder** [comment]
Hi @bianhaotian ,

Thank you for your question. It seems like you run into issues with statistical estimation while assessing mediation using the RI-CLPM. The warning message points to the random intercept factor `RIY` as the problematic latent variable. You could check if this factor has a variance estimate that is negative. One reason why this might happen, is because you included lag-2 effects $X_{1} \rightarrow Y_{3}$ and $Y_{1} \rightarrow X_{3}$ in the within part of the model. These lag-2 effects can model longer term effects between variables, which, in an RI-CLPM with only lag-1 effects, might be absorbed by the covariance between the random intercept factors of $X$ and $Y$ instead. Now that the lag-2 term relation between X and Y can be modelled at the within-part of the model, there remains only very little variance for one of the random intercept factor, which is then estimated to have a variance that might be negative. This would be my first guess (in laymen's terms) of why you get this warning. 

Finally, I have added some concerns that warrant consideration when doing mediation analysis using the RI-CLPM in the [FAQ's on the website](https://jeroendmulder.github.io/RI-CLPM/faq.html#moderation-and-mediation).  You might find these useful as well.

**Comment by psyhtbian** [comment]
You are so nice, I tried to not set the covariance of the between-person part and than model runs normally, do you recommend this setting?
