### ISSUE TITLE
RI-CLPM - LAVAAN-Code - Constrain standardized lagged effects

### ISSUE THREAD

**Issue by Splaesch** [JeroenDMulder/RI-CLPM#6]
Hello Jeroen Mulder, 

first, thank you for providing the R/LAVAAN-code for the RI-CLPM (https://jeroendmulder.github.io/RI-CLPM/lavaan.html) online and free! 

Now, I am not an expert, but was wondering about the code for the "Constrain standardized lagged effects" (No extension).
In general, you treat all (in your example) 5 waves the same (except for wave 1), all get the same treatment. But this is not the case in the following section: 

 # Compute correlations of within-components at each wave
  cor2 := a*c + b*d + a*d*cor1 + b*c*cor1 + rcov2
  cor3 := a*c + b*d + a*d*cor2 + b*c*cor2 + rcov3
  cor4 := a*c + b*d + a*d*cor3 + b*c*cor3 + rcov4

There you define only cor2-cor4 and I wonder why you don't define cor5? 
In my current study I have only four waves anyways. I used your code by cutting out all variables concerning wave 5, but in the upper section I didn't have to cut anything out, which feels a bit odd. 

Isn't there this missing:?
  cor5 := a*c + b*d + a*d*cor4 + b*c*cor4 + rcov5

Maybe it is intended. as you did. Like I said, I am not an expert but I noticed it mismatching somehow and wanted to tell. 

Have a nice day! 
Korbinan

**Comment by JeroenDMulder** [comment]
Hello @Splaesch, thank you for your question. The reason why you don't need to specify `cor5`, is because the variances of the within-components are functions of lagged parameters, and the covariances between the *lagged* predictors (not the covariances at the same wave). So, for computing the residual variances of the within-components at wave 5, we need the covariances of wave 4 (the lagged predictor). Note that, since we are imposing constraints such that the variances of the within-components are one, these covariances are now correlations, hence the label `cor`.

**Comment by Splaesch** [comment]
Hello @JeroenDMulder ,

thank you a lot for clarifying my question with your comment and explanation, it helped me a lot! 

Best wishes, 
Splaesch
